
-- ==============================================
-- Script de Creación de Tablas - Reto 4 SGBD
-- ==============================================

-- Eliminar las tablas si existen previamente
DROP TABLE Pedidos CASCADE CONSTRAINTS;
DROP TABLE Clientes CASCADE CONSTRAINTS;

-- Crear tabla Clientes
CREATE TABLE Clientes (
    ClienteID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Direccion VARCHAR2(150),
    Telefono VARCHAR2(20)
);

-- Crear tabla Pedidos
CREATE TABLE Pedidos (
    PedidoID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClienteID NUMBER NOT NULL,
    FechaPedido DATE DEFAULT SYSDATE,
    Detalle VARCHAR2(200),
    Monto NUMBER(10, 2),
    CONSTRAINT fk_cliente FOREIGN KEY (ClienteID) REFERENCES Clientes(ClienteID) ON DELETE CASCADE
);
